export const MONGODB_CONNECTION_URI = 'mongodb://localhost/kittens'
export const DATABASE_INJECTION_KEY = 'DATABASE_CONNECTION'
export const KITTEN_MODEL_INJECTION_KEY = 'KITTEN_MODEL'
export const USER_MODEL_INJECTION_KEY = 'USER_MODEL'